<?php

$csv = static fn (string $key, string $default): array => array_values(array_filter(array_map(
    static fn (string $value): string => trim($value),
    explode(',', (string) env($key, $default)),
)));

return [
    'enabled' => env('NUCLEI_ENABLED', false),
    'version' => env('NUCLEI_VERSION', null),
    'binary_path' => env('NUCLEI_BINARY_PATH', '/usr/local/bin/nuclei'),
    'templates_path' => env('NUCLEI_TEMPLATES_PATH', '/opt/nuclei-templates'),
    'default_timeout_seconds' => env('NUCLEI_DEFAULT_TIMEOUT_SECONDS', 300),
    'max_requests' => env('NUCLEI_MAX_REQUESTS', 100),
    'rate_limit_per_second' => env('NUCLEI_RATE_LIMIT_PER_SECOND', 2),
    'allowed_severities' => $csv('NUCLEI_ALLOWED_SEVERITIES', 'info,low,medium,high,critical'),
    'safe_template_tags' => $csv('NUCLEI_SAFE_TEMPLATE_TAGS', 'exposure,misconfig,headers,ssl,tech,cve,config'),
    'blocked_template_tags' => $csv('NUCLEI_BLOCKED_TEMPLATE_TAGS', 'dos,fuzz,fuzzing,brute-force,bruteforce,intrusive,destructive,aggressive,dast'),
    'sandbox_root' => env('SCANFORGE_SCANNER_TMP', '/tmp/scanforge'),
    'integration_test' => env('NUCLEI_INTEGRATION_TEST', false),

    'policies' => [
        [
            'template_group' => 'laravel/*',
            'allowed' => true,
            'safety_level' => 'safe',
            'allowed_tags' => ['exposure', 'misconfig', 'cve', 'config'],
            'reason' => 'Laravel safe exposure, config and CVE checks from scan plan recommendations.',
        ],
        [
            'template_group' => 'nginx/*',
            'allowed' => true,
            'safety_level' => 'safe',
            'allowed_tags' => ['headers', 'misconfig', 'exposure', 'config'],
            'reason' => 'Nginx header, exposure and configuration posture checks.',
        ],
        [
            'template_group' => 'apache/*',
            'allowed' => true,
            'safety_level' => 'safe',
            'allowed_tags' => ['headers', 'misconfig', 'exposure', 'config'],
            'reason' => 'Apache header, exposure and configuration posture checks.',
        ],
        [
            'template_group' => 'nextjs/*',
            'allowed' => true,
            'safety_level' => 'safe',
            'allowed_tags' => ['exposure', 'misconfig', 'cve', 'config'],
            'reason' => 'Next.js safe exposure, misconfiguration and known CVE checks.',
        ],
        [
            'template_group' => 'iis/aspnet/*',
            'allowed' => true,
            'safety_level' => 'safe',
            'allowed_tags' => ['headers', 'misconfig', 'exposure', 'cve', 'config'],
            'reason' => 'IIS and ASP.NET safe checks selected by technology fingerprinting.',
        ],
        [
            'template_group' => 'php/*',
            'allowed' => true,
            'safety_level' => 'safe',
            'allowed_tags' => ['exposure', 'misconfig', 'cve', 'config'],
            'reason' => 'PHP safe exposure and known vulnerability checks.',
        ],
        [
            'template_group' => 'exposures',
            'allowed' => true,
            'safety_level' => 'safe',
            'allowed_tags' => ['exposure'],
            'reason' => 'Safe exposure detection without intrusive payloads.',
        ],
        [
            'template_group' => 'misconfig',
            'allowed' => true,
            'safety_level' => 'safe',
            'allowed_tags' => ['misconfig', 'config'],
            'reason' => 'Safe configuration posture checks.',
        ],
        [
            'template_group' => 'headers',
            'allowed' => true,
            'safety_level' => 'safe',
            'allowed_tags' => ['headers'],
            'reason' => 'HTTP header posture checks.',
        ],
        [
            'template_group' => 'ssl',
            'allowed' => true,
            'safety_level' => 'safe',
            'allowed_tags' => ['ssl', 'tls'],
            'reason' => 'TLS and certificate posture checks.',
        ],
        [
            'template_group' => 'technologies',
            'allowed' => true,
            'safety_level' => 'safe',
            'allowed_tags' => ['tech', 'technologies'],
            'reason' => 'Technology detection templates safe for verified assets.',
        ],
        [
            'template_group' => 'cves',
            'allowed' => true,
            'safety_level' => 'safe',
            'allowed_tags' => ['cve'],
            'reason' => 'Only safe CVE templates are allowed; blocked tags still override this group.',
        ],
        [
            'template_group' => 'dos',
            'allowed' => false,
            'safety_level' => 'blocked',
            'blocked_tags' => ['dos'],
            'reason' => 'Denial-of-service templates are not allowed in Phase 06.',
        ],
        [
            'template_group' => 'fuzz',
            'allowed' => false,
            'safety_level' => 'blocked',
            'blocked_tags' => ['fuzz', 'fuzzing', 'dast'],
            'reason' => 'Fuzzing templates are out of scope for Phase 06.',
        ],
        [
            'template_group' => 'brute',
            'allowed' => false,
            'safety_level' => 'blocked',
            'blocked_tags' => ['brute-force', 'bruteforce'],
            'reason' => 'Brute-force templates are not allowed.',
        ],
        [
            'template_group' => 'intrusive',
            'allowed' => false,
            'safety_level' => 'blocked',
            'blocked_tags' => ['intrusive'],
            'reason' => 'Intrusive checks require a later explicit phase.',
        ],
        [
            'template_group' => 'destructive',
            'allowed' => false,
            'safety_level' => 'blocked',
            'blocked_tags' => ['destructive'],
            'reason' => 'Destructive checks are never part of safe default execution.',
        ],
        [
            'template_group' => 'exploit-aggressive',
            'allowed' => false,
            'safety_level' => 'blocked',
            'blocked_tags' => ['exploit', 'aggressive'],
            'reason' => 'Aggressive exploit-heavy checks are out of scope.',
        ],
    ],

    'template_manifest' => [
        ['template_id' => 'scanforge-safe-exposures', 'group' => 'exposures', 'severity' => 'info', 'tags' => ['exposure'], 'author' => 'scanforge', 'signed' => false],
        ['template_id' => 'scanforge-safe-misconfig', 'group' => 'misconfig', 'severity' => 'low', 'tags' => ['misconfig', 'config'], 'author' => 'scanforge', 'signed' => false],
        ['template_id' => 'scanforge-safe-headers', 'group' => 'headers', 'severity' => 'info', 'tags' => ['headers'], 'author' => 'scanforge', 'signed' => false],
        ['template_id' => 'scanforge-safe-ssl', 'group' => 'ssl', 'severity' => 'low', 'tags' => ['ssl', 'tls'], 'author' => 'scanforge', 'signed' => false],
        ['template_id' => 'scanforge-safe-technologies', 'group' => 'technologies', 'severity' => 'info', 'tags' => ['tech'], 'author' => 'scanforge', 'signed' => false],
        ['template_id' => 'scanforge-safe-cves', 'group' => 'cves', 'severity' => 'medium', 'tags' => ['cve'], 'author' => 'scanforge', 'signed' => false],
    ],
];
