<?php

return [
    [
        'technology_key' => 'laravel',
        'scanner_key' => 'nuclei',
        'template_group' => 'laravel/*',
        'scan_module' => 'framework-cves',
        'min_confidence' => 70,
        'min_version' => null,
        'max_version' => null,
        'supported_versions' => ['10.x', '11.x', '12.x'],
        'enabled' => true,
        'safe_default' => true,
        'priority' => 82,
        'estimated_duration_seconds' => 180,
        'estimated_requests' => 80,
        'estimated_cpu' => 0.35,
        'estimated_memory_mb' => 256,
        'safe_mode' => true,
        'description' => 'Laravel-specific exposure and known vulnerability templates.',
    ],
    [
        'technology_key' => 'wordpress',
        'scanner_key' => 'wpscan',
        'template_group' => 'core/plugins/themes',
        'scan_module' => 'cms-inventory',
        'min_confidence' => 75,
        'min_version' => null,
        'max_version' => null,
        'supported_versions' => ['4.x', '5.x', '6.x'],
        'enabled' => true,
        'safe_default' => true,
        'priority' => 88,
        'estimated_duration_seconds' => 300,
        'estimated_requests' => 180,
        'estimated_cpu' => 0.45,
        'estimated_memory_mb' => 384,
        'safe_mode' => true,
        'description' => 'WordPress core, plugin and theme inventory checks.',
    ],
    [
        'technology_key' => 'nginx',
        'scanner_key' => 'nuclei',
        'template_group' => 'nginx/*',
        'scan_module' => 'server-hardening',
        'min_confidence' => 60,
        'min_version' => null,
        'max_version' => null,
        'supported_versions' => null,
        'enabled' => true,
        'safe_default' => true,
        'priority' => 70,
        'estimated_duration_seconds' => 120,
        'estimated_requests' => 60,
        'estimated_cpu' => 0.25,
        'estimated_memory_mb' => 192,
        'safe_mode' => true,
        'description' => 'Nginx configuration and exposure templates.',
    ],
    [
        'technology_key' => 'apache',
        'scanner_key' => 'nuclei',
        'template_group' => 'apache/*',
        'scan_module' => 'server-hardening',
        'min_confidence' => 60,
        'min_version' => null,
        'max_version' => null,
        'supported_versions' => null,
        'enabled' => true,
        'safe_default' => true,
        'priority' => 70,
        'estimated_duration_seconds' => 120,
        'estimated_requests' => 60,
        'estimated_cpu' => 0.25,
        'estimated_memory_mb' => 192,
        'safe_mode' => true,
        'description' => 'Apache HTTP Server configuration and exposure templates.',
    ],
    [
        'technology_key' => 'nextjs',
        'scanner_key' => 'nuclei',
        'template_group' => 'nextjs/*',
        'scan_module' => 'framework-cves',
        'min_confidence' => 70,
        'min_version' => null,
        'max_version' => null,
        'supported_versions' => ['12.x', '13.x', '14.x', '15.x'],
        'enabled' => true,
        'safe_default' => true,
        'priority' => 78,
        'estimated_duration_seconds' => 160,
        'estimated_requests' => 75,
        'estimated_cpu' => 0.30,
        'estimated_memory_mb' => 256,
        'safe_mode' => true,
        'description' => 'Next.js specific exposure and version-aware template group.',
    ],
    [
        'technology_key' => 'aspnet',
        'scanner_key' => 'nuclei',
        'template_group' => 'iis/aspnet/*',
        'scan_module' => 'framework-cves',
        'min_confidence' => 70,
        'min_version' => null,
        'max_version' => null,
        'supported_versions' => null,
        'enabled' => true,
        'safe_default' => true,
        'priority' => 74,
        'estimated_duration_seconds' => 180,
        'estimated_requests' => 80,
        'estimated_cpu' => 0.35,
        'estimated_memory_mb' => 256,
        'safe_mode' => true,
        'description' => 'IIS and ASP.NET checks selected by technology fingerprinting.',
    ],
    [
        'technology_key' => 'cloudflare',
        'scanner_key' => 'headers-dns',
        'template_group' => 'cloudflare-checks',
        'scan_module' => 'edge-posture',
        'min_confidence' => 65,
        'min_version' => null,
        'max_version' => null,
        'supported_versions' => null,
        'enabled' => true,
        'safe_default' => true,
        'priority' => 66,
        'estimated_duration_seconds' => 90,
        'estimated_requests' => 30,
        'estimated_cpu' => 0.10,
        'estimated_memory_mb' => 128,
        'safe_mode' => true,
        'description' => 'Cloudflare DNS and security header posture checks.',
    ],
    [
        'technology_key' => 'php',
        'scanner_key' => 'nuclei',
        'template_group' => 'php/*',
        'scan_module' => 'language-cves',
        'min_confidence' => 65,
        'min_version' => null,
        'max_version' => null,
        'supported_versions' => ['7.x', '8.x'],
        'enabled' => true,
        'safe_default' => true,
        'priority' => 72,
        'estimated_duration_seconds' => 140,
        'estimated_requests' => 65,
        'estimated_cpu' => 0.25,
        'estimated_memory_mb' => 192,
        'safe_mode' => true,
        'description' => 'PHP version-aware exposure checks selected from passive fingerprinting.',
    ],
    [
        'technology_key' => 'wordpress',
        'scanner_key' => 'cms_scanner',
        'template_group' => 'native',
        'scan_module' => 'wordpress_cms',
        'min_confidence' => 40,
        'enabled' => true,
        'safe_default' => true,
        'priority' => 15,
        'description' => 'Native WordPress CMS basic checks.',
    ],
    [
        'technology_key' => 'generic_cms',
        'scanner_key' => 'cms_scanner',
        'template_group' => 'native',
        'scan_module' => 'generic_cms',
        'min_confidence' => 40,
        'enabled' => true,
        'safe_default' => true,
        'priority' => 15,
        'description' => 'Native Generic CMS basic checks.',
    ],
];
